/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Crud.CrudCliente;
import Crud.CrudFuncionario;
import Crud.CrudProduto;
import Crud.CrudVenda;
import Domain.Cliente;
import Domain.Funcionario;
import Domain.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author ninag
 */
public class IFrmNovaVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmNovaVenda
     */
    public IFrmNovaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDados = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        lbFuncionario = new javax.swing.JLabel();
        lbProduto = new javax.swing.JLabel();
        lbQuantidade = new javax.swing.JLabel();
        lbRota = new javax.swing.JLabel();
        lbPrevisaoEntrega = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        tfDataVenda = new javax.swing.JTextField();
        tfIdClienteVenda = new javax.swing.JTextField();
        tfIdFuncionarioVenda = new javax.swing.JTextField();
        tfIdProdutoVenda = new javax.swing.JTextField();
        tfQuantidadeVenda = new javax.swing.JTextField();
        tfRotaVenda = new javax.swing.JTextField();
        tfPrevisaoEntregaVenda = new javax.swing.JTextField();

        setTitle("Nova Venda");

        lbDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDados.setText("Informe os dados da Venda");

        lbData.setText("Data");

        lbCliente.setText("ID do Cliente");

        lbFuncionario.setText("ID do Vendedor");

        lbProduto.setText("ID do Produto");

        lbQuantidade.setText("Quantidade");

        lbRota.setText("Rota");

        lbPrevisaoEntrega.setText("Previsão de Entrega");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lbDados)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCadastrar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPrevisaoEntrega)
                    .addComponent(lbRota)
                    .addComponent(lbFuncionario)
                    .addComponent(lbCliente)
                    .addComponent(lbData)
                    .addComponent(lbProduto)
                    .addComponent(lbQuantidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfQuantidadeVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                        .addComponent(tfIdProdutoVenda, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfIdFuncionarioVenda, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfIdClienteVenda, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(tfRotaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrevisaoEntregaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbData)
                    .addComponent(tfDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCliente)
                    .addComponent(tfIdClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFuncionario)
                    .addComponent(tfIdFuncionarioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduto)
                    .addComponent(tfIdProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidade)
                    .addComponent(tfQuantidadeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfRotaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRota))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrevisaoEntrega)
                    .addComponent(tfPrevisaoEntregaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        JOptionPane.showMessageDialog(null, "Cancelado!");
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        CrudVenda crudVenda = new CrudVenda();
        CrudCliente crudCliente = new CrudCliente();
        CrudFuncionario crudFuncionario = new CrudFuncionario();
        CrudProduto crudProduto = new CrudProduto();
        Cliente c = crudCliente.pesquisarCliente(Integer.parseInt(tfIdClienteVenda.getText()));
        Funcionario f = crudFuncionario.pesquisarFuncionario(Integer.parseInt(tfIdFuncionarioVenda.getText()));
        Produto p = crudProduto.pesquisarProduto(Integer.parseInt(tfIdProdutoVenda.getText())); 
        crudVenda.NovaVenda(tfDataVenda.getText(), c, f, tfPrevisaoEntregaVenda.getText(), 
                tfRotaVenda.getText(), 
                p, Integer.parseInt(tfQuantidadeVenda.getText()));
        JOptionPane.showMessageDialog(null, "Venda Cadastrada!");
        this.dispose();
    }//GEN-LAST:event_btCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbDados;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbFuncionario;
    private javax.swing.JLabel lbPrevisaoEntrega;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JLabel lbRota;
    private javax.swing.JTextField tfDataVenda;
    private javax.swing.JTextField tfIdClienteVenda;
    private javax.swing.JTextField tfIdFuncionarioVenda;
    private javax.swing.JTextField tfIdProdutoVenda;
    private javax.swing.JTextField tfPrevisaoEntregaVenda;
    private javax.swing.JTextField tfQuantidadeVenda;
    private javax.swing.JTextField tfRotaVenda;
    // End of variables declaration//GEN-END:variables
}
