/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Crud.CrudCliente;
import Crud.CrudEntrega;
import Crud.CrudFuncao;
import Crud.CrudFuncionario;
import Crud.CrudProduto;
import Crud.CrudUsuario;
import Crud.CrudVenda;
import Domain.Cliente;
import Domain.Entrega;
import Domain.Funcao;
import Domain.Funcionario;
import Domain.Produto;
import Domain.Usuario;
import Domain.Venda;
import javax.swing.JOptionPane;

/**
 *
 * @author thiag
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMenuPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mbMenuPrincipal = new javax.swing.JMenuBar();
        jCadastro = new javax.swing.JMenu();
        jCliente = new javax.swing.JMenu();
        jNovoCliente = new javax.swing.JMenuItem();
        jAlterarCliente = new javax.swing.JMenuItem();
        jVisualizarCliente = new javax.swing.JMenuItem();
        jExcluirCliente = new javax.swing.JMenuItem();
        jEntrega = new javax.swing.JMenu();
        jNovaEntrega = new javax.swing.JMenuItem();
        jAlterarEnrtega = new javax.swing.JMenuItem();
        jVisualizarEntrega = new javax.swing.JMenuItem();
        jExcluirEntrega = new javax.swing.JMenuItem();
        jFuncao = new javax.swing.JMenu();
        jNovaFuncao = new javax.swing.JMenuItem();
        jAlterarFuncao = new javax.swing.JMenuItem();
        jVisualizarFuncao = new javax.swing.JMenuItem();
        jExcluirFuncao = new javax.swing.JMenuItem();
        jFuncionario = new javax.swing.JMenu();
        jNovoFuncionario = new javax.swing.JMenuItem();
        jAlterarFuncionaro = new javax.swing.JMenuItem();
        jVisualizarFuncionario = new javax.swing.JMenuItem();
        jExcluirFuncionario = new javax.swing.JMenuItem();
        jProduto = new javax.swing.JMenu();
        jNovoProduto = new javax.swing.JMenuItem();
        jAlterarProduto = new javax.swing.JMenuItem();
        jVisualizarProduto = new javax.swing.JMenuItem();
        jExcluirProduto = new javax.swing.JMenuItem();
        jUsuario = new javax.swing.JMenu();
        jNovoUsuario = new javax.swing.JMenuItem();
        jAlterarUsuario = new javax.swing.JMenuItem();
        jVisualizarUsuario = new javax.swing.JMenuItem();
        jExcluirUsuario = new javax.swing.JMenuItem();
        jVenda = new javax.swing.JMenu();
        jNovaVenda = new javax.swing.JMenuItem();
        jAlterarVenda = new javax.swing.JMenuItem();
        jVisualizarVenda = new javax.swing.JMenuItem();
        jExcluirVenda = new javax.swing.JMenuItem();
        jListagem = new javax.swing.JMenu();
        listCliente = new javax.swing.JMenuItem();
        listEntrega = new javax.swing.JMenuItem();
        listFuncao = new javax.swing.JMenuItem();
        listFuncionario = new javax.swing.JMenuItem();
        listProduto = new javax.swing.JMenuItem();
        listUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IMG_Menu_Principal.jpg"))); // NOI18N

        dpMenuPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpMenuPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpMenuPrincipalLayout = new javax.swing.GroupLayout(dpMenuPrincipal);
        dpMenuPrincipal.setLayout(dpMenuPrincipalLayout);
        dpMenuPrincipalLayout.setHorizontalGroup(
            dpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpMenuPrincipalLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel2)
                .addGap(73, 73, 73)
                .addComponent(jLabel1))
        );
        dpMenuPrincipalLayout.setVerticalGroup(
            dpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpMenuPrincipalLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jCadastro.setText("Cadastro");

        jCliente.setText("Cliente");

        jNovoCliente.setText("Novo Cliente");
        jNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoClienteActionPerformed(evt);
            }
        });
        jCliente.add(jNovoCliente);

        jAlterarCliente.setText("Alterar Cliente");
        jAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarClienteActionPerformed(evt);
            }
        });
        jCliente.add(jAlterarCliente);

        jVisualizarCliente.setText("Visualizar Cliente");
        jVisualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisualizarClienteActionPerformed(evt);
            }
        });
        jCliente.add(jVisualizarCliente);

        jExcluirCliente.setText("Excluir Cliente");
        jExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirClienteActionPerformed(evt);
            }
        });
        jCliente.add(jExcluirCliente);

        jCadastro.add(jCliente);

        jEntrega.setText("Entrega");

        jNovaEntrega.setText("Nova Entrega");
        jNovaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovaEntregaActionPerformed(evt);
            }
        });
        jEntrega.add(jNovaEntrega);

        jAlterarEnrtega.setText("Alterar Entrega");
        jAlterarEnrtega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarEnrtegaActionPerformed(evt);
            }
        });
        jEntrega.add(jAlterarEnrtega);

        jVisualizarEntrega.setText("Visualizar Entrega");
        jVisualizarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisualizarEntregaActionPerformed(evt);
            }
        });
        jEntrega.add(jVisualizarEntrega);

        jExcluirEntrega.setText("Excluir Entrega");
        jExcluirEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirEntregaActionPerformed(evt);
            }
        });
        jEntrega.add(jExcluirEntrega);

        jCadastro.add(jEntrega);

        jFuncao.setText("Função");

        jNovaFuncao.setText("Nova Função");
        jNovaFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovaFuncaoActionPerformed(evt);
            }
        });
        jFuncao.add(jNovaFuncao);

        jAlterarFuncao.setText("Alterar Função");
        jAlterarFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarFuncaoActionPerformed(evt);
            }
        });
        jFuncao.add(jAlterarFuncao);

        jVisualizarFuncao.setText("Visualizar Função");
        jVisualizarFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisualizarFuncaoActionPerformed(evt);
            }
        });
        jFuncao.add(jVisualizarFuncao);

        jExcluirFuncao.setText("Excluir Função");
        jExcluirFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirFuncaoActionPerformed(evt);
            }
        });
        jFuncao.add(jExcluirFuncao);

        jCadastro.add(jFuncao);

        jFuncionario.setText("Funcionário");

        jNovoFuncionario.setText("Novo Funcionário");
        jNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoFuncionarioActionPerformed(evt);
            }
        });
        jFuncionario.add(jNovoFuncionario);

        jAlterarFuncionaro.setText("Alterar Funcionáro");
        jAlterarFuncionaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarFuncionaroActionPerformed(evt);
            }
        });
        jFuncionario.add(jAlterarFuncionaro);

        jVisualizarFuncionario.setText("Visualizar Funcionário");
        jVisualizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisualizarFuncionarioActionPerformed(evt);
            }
        });
        jFuncionario.add(jVisualizarFuncionario);

        jExcluirFuncionario.setText("Excluir Funcionário");
        jExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirFuncionarioActionPerformed(evt);
            }
        });
        jFuncionario.add(jExcluirFuncionario);

        jCadastro.add(jFuncionario);

        jProduto.setText("Produto");

        jNovoProduto.setText("Novo Produto");
        jNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoProdutoActionPerformed(evt);
            }
        });
        jProduto.add(jNovoProduto);

        jAlterarProduto.setText("Alterar Produto");
        jAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarProdutoActionPerformed(evt);
            }
        });
        jProduto.add(jAlterarProduto);

        jVisualizarProduto.setText("Visualizar Produto");
        jVisualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisualizarProdutoActionPerformed(evt);
            }
        });
        jProduto.add(jVisualizarProduto);

        jExcluirProduto.setText("Excluir Produto");
        jExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirProdutoActionPerformed(evt);
            }
        });
        jProduto.add(jExcluirProduto);

        jCadastro.add(jProduto);

        jUsuario.setText("Usuário");

        jNovoUsuario.setText("Novo Usuário");
        jNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoUsuarioActionPerformed(evt);
            }
        });
        jUsuario.add(jNovoUsuario);

        jAlterarUsuario.setText("Alterar Usuário");
        jAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarUsuarioActionPerformed(evt);
            }
        });
        jUsuario.add(jAlterarUsuario);

        jVisualizarUsuario.setText("Visualizar Usuário");
        jVisualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisualizarUsuarioActionPerformed(evt);
            }
        });
        jUsuario.add(jVisualizarUsuario);

        jExcluirUsuario.setText("Excluir Usuário");
        jExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirUsuarioActionPerformed(evt);
            }
        });
        jUsuario.add(jExcluirUsuario);

        jCadastro.add(jUsuario);

        jVenda.setText("Venda");

        jNovaVenda.setText("Nova Venda");
        jNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovaVendaActionPerformed(evt);
            }
        });
        jVenda.add(jNovaVenda);

        jAlterarVenda.setText("Alterar Venda");
        jAlterarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarVendaActionPerformed(evt);
            }
        });
        jVenda.add(jAlterarVenda);

        jVisualizarVenda.setText("Visualizar Venda");
        jVisualizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisualizarVendaActionPerformed(evt);
            }
        });
        jVenda.add(jVisualizarVenda);

        jExcluirVenda.setText("Excluir Venda");
        jExcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirVendaActionPerformed(evt);
            }
        });
        jVenda.add(jExcluirVenda);

        jCadastro.add(jVenda);

        mbMenuPrincipal.add(jCadastro);

        jListagem.setText("Listagem");

        listCliente.setText("Cliente");
        listCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClienteActionPerformed(evt);
            }
        });
        jListagem.add(listCliente);

        listEntrega.setText("Entrega");
        listEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEntregaActionPerformed(evt);
            }
        });
        jListagem.add(listEntrega);

        listFuncao.setText("Função");
        listFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listFuncaoActionPerformed(evt);
            }
        });
        jListagem.add(listFuncao);

        listFuncionario.setText("Funcionário");
        listFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listFuncionarioActionPerformed(evt);
            }
        });
        jListagem.add(listFuncionario);

        listProduto.setText("Produto");
        listProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listProdutoActionPerformed(evt);
            }
        });
        jListagem.add(listProduto);

        listUsuario.setText("Usuário");
        listUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUsuarioActionPerformed(evt);
            }
        });
        jListagem.add(listUsuario);

        jMenuItem1.setText("Venda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jListagem.add(jMenuItem1);

        mbMenuPrincipal.add(jListagem);

        setJMenuBar(mbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMenuPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMenuPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoClienteActionPerformed
        IFrmNovoCliente ifrmNovoCliente = new IFrmNovoCliente();
        dpMenuPrincipal.add(ifrmNovoCliente);
        ifrmNovoCliente.setVisible(true);
    }//GEN-LAST:event_jNovoClienteActionPerformed

    private void jAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarClienteActionPerformed
        CrudCliente crudCliente = new CrudCliente();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do Cliente"));
        Cliente c = crudCliente.pesquisarCliente(id);
        if (c == null) {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
        } else {
            IFrmAlterarCliente ifrmAlterarCliente = new IFrmAlterarCliente(c);
            dpMenuPrincipal.add(ifrmAlterarCliente);
            ifrmAlterarCliente.setVisible(true);
        }
    }//GEN-LAST:event_jAlterarClienteActionPerformed

    private void jExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirClienteActionPerformed
        String visualizar;
        CrudCliente crudCliente = new CrudCliente();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do Cliente"));
        Cliente c = crudCliente.pesquisarCliente(id);
        if (c == null) {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
        } else {
            IFrmExcluirCliente ifrmExcluirCliente = new IFrmExcluirCliente(c);
            dpMenuPrincipal.add(ifrmExcluirCliente);
            ifrmExcluirCliente.setVisible(true);
        }
    }//GEN-LAST:event_jExcluirClienteActionPerformed

    private void jVisualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisualizarClienteActionPerformed
        CrudCliente crudCliente = new CrudCliente();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do Cliente"));
        Cliente c = crudCliente.pesquisarCliente(id);
        if (c == null) {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
        } else {
            IFrmVisualizarCliente ifrmVisualizarCliente = new IFrmVisualizarCliente(c);
            dpMenuPrincipal.add(ifrmVisualizarCliente);
            ifrmVisualizarCliente.setVisible(true);
        }
    }//GEN-LAST:event_jVisualizarClienteActionPerformed

    private void jNovaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovaEntregaActionPerformed
        IFrmNovaEntrega ifrmNovaEntrega = new IFrmNovaEntrega();
        dpMenuPrincipal.add(ifrmNovaEntrega);
        ifrmNovaEntrega.setVisible(true);
    }//GEN-LAST:event_jNovaEntregaActionPerformed

    private void jAlterarEnrtegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarEnrtegaActionPerformed
        CrudEntrega crudEntrega = new CrudEntrega();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Entrega"));
        Entrega e =  crudEntrega.pesquisarEntrega(id);
        if(e == null){
            JOptionPane.showMessageDialog(null, "Entrega não encontrada!");
        }else{
            IFrmAlterarEntrega ifrmAlterarEntrega = new IFrmAlterarEntrega(e);
            dpMenuPrincipal.add(ifrmAlterarEntrega);
            ifrmAlterarEntrega.setVisible(true);
        }
    }//GEN-LAST:event_jAlterarEnrtegaActionPerformed

    private void jVisualizarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisualizarEntregaActionPerformed
        CrudEntrega crudEntrega = new CrudEntrega();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Entrega"));
        Entrega e =  crudEntrega.pesquisarEntrega(id);
        if(e == null){
            JOptionPane.showMessageDialog(null, "Entrega não encontrada!");
        }else{
            IFrmVisualizarEntrega ifrmVisualizarEntrega = new IFrmVisualizarEntrega(e);
            dpMenuPrincipal.add(ifrmVisualizarEntrega);
            ifrmVisualizarEntrega.setVisible(true);
        }
    }//GEN-LAST:event_jVisualizarEntregaActionPerformed

    private void jExcluirEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirEntregaActionPerformed
        CrudEntrega crudEntrega = new CrudEntrega();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Entrega"));
        Entrega e =  crudEntrega.pesquisarEntrega(id);
        if(e == null){
            JOptionPane.showMessageDialog(null, "Entrega não encontrada!");
        }else{
            IFrmExcluirEntrega ifrmExcluirEntrega = new IFrmExcluirEntrega(e);
            dpMenuPrincipal.add(ifrmExcluirEntrega);
            ifrmExcluirEntrega.setVisible(true);
        }
    }//GEN-LAST:event_jExcluirEntregaActionPerformed

    private void jNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoUsuarioActionPerformed
        IFrmNovoUsuario ifrmNovoUsuario = new IFrmNovoUsuario();
        dpMenuPrincipal.add(ifrmNovoUsuario);
        ifrmNovoUsuario.setVisible(true);
    }//GEN-LAST:event_jNovoUsuarioActionPerformed

    private void jAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarUsuarioActionPerformed
        CrudUsuario crudUsuario = new CrudUsuario();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do Usuário"));
        Usuario u = crudUsuario.PesquisarUsuario(id);
        if(u == null){
            JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
        }else{
            IFrmAlterarUsuario ifrmAlterarUsuario = new IFrmAlterarUsuario(u);
            dpMenuPrincipal.add(ifrmAlterarUsuario);
            ifrmAlterarUsuario.setVisible(true);
        }
    }//GEN-LAST:event_jAlterarUsuarioActionPerformed

    private void jVisualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisualizarUsuarioActionPerformed
        CrudUsuario crudUsuario = new CrudUsuario();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do Usuário"));
        Usuario u = crudUsuario.PesquisarUsuario(id);
        if(u == null){
            JOptionPane.showMessageDialog(null, "Usuário não encontrado");
        }else{
            IFrmVisualizarUsuario ifrmVisualizarUsuario = new IFrmVisualizarUsuario(u);
            dpMenuPrincipal.add(ifrmVisualizarUsuario);
            ifrmVisualizarUsuario.setVisible(true);
        }
    }//GEN-LAST:event_jVisualizarUsuarioActionPerformed

    private void jExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirUsuarioActionPerformed
        CrudUsuario crudUsuario = new CrudUsuario();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do Usuário"));
        Usuario u = crudUsuario.PesquisarUsuario(id);
        if(u == null){
            JOptionPane.showMessageDialog(null, "Usuário não encontrado");
        }else{
            IFrmExcluirUsuario ifrmExcluirUsuario = new IFrmExcluirUsuario(u);
            dpMenuPrincipal.add(ifrmExcluirUsuario);
            ifrmExcluirUsuario.setVisible(true);
        }
    }//GEN-LAST:event_jExcluirUsuarioActionPerformed

    private void jNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovaVendaActionPerformed
        IFrmNovaVenda ifrmNovaVenda = new IFrmNovaVenda();
        dpMenuPrincipal.add(ifrmNovaVenda);
        ifrmNovaVenda.setVisible(true);
    }//GEN-LAST:event_jNovaVendaActionPerformed

    private void jAlterarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarVendaActionPerformed
        CrudVenda crudVenda = new CrudVenda();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Venda"));
        Venda v = crudVenda.VisualizarVenda(id);
        if(v == null){
            JOptionPane.showMessageDialog(null, "Venda não encontrada!");
        }else{
            IFrmAlterarVenda ifrmAlterarVenda = new IFrmAlterarVenda(v);
            dpMenuPrincipal.add(ifrmAlterarVenda);
            ifrmAlterarVenda.setVisible(true);
        }
    }//GEN-LAST:event_jAlterarVendaActionPerformed

    private void jVisualizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisualizarVendaActionPerformed
        CrudVenda crudVenda = new CrudVenda();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Venda"));
        Venda v = crudVenda.VisualizarVenda(id);
        if(v == null){
            JOptionPane.showMessageDialog(null, "Venda não encontrada!");
        }else{
            IFrmVisualizarVenda ifrmVisualizarVenda = new IFrmVisualizarVenda(v);
            dpMenuPrincipal.add(ifrmVisualizarVenda);
            ifrmVisualizarVenda.setVisible(true);
        }
    }//GEN-LAST:event_jVisualizarVendaActionPerformed

    private void jExcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirVendaActionPerformed
        CrudVenda crudVenda = new CrudVenda();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Venda"));
        Venda v = crudVenda.VisualizarVenda(id);
        if(v == null){
            JOptionPane.showMessageDialog(null, "Venda não encontrada!");
        }else{
            IFrmExcluirVenda ifrmExcluirVenda = new IFrmExcluirVenda(v);
            dpMenuPrincipal.add(ifrmExcluirVenda);
            ifrmExcluirVenda.setVisible(true);
        }
    }//GEN-LAST:event_jExcluirVendaActionPerformed

    private void jNovaFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovaFuncaoActionPerformed
        IFrmNovaFuncao ifrmNovaFuncao = new IFrmNovaFuncao();
        dpMenuPrincipal.add(ifrmNovaFuncao);
        ifrmNovaFuncao.setVisible(true);
    }//GEN-LAST:event_jNovaFuncaoActionPerformed

    private void jAlterarFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarFuncaoActionPerformed
        CrudFuncao crudFuncao = new CrudFuncao();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Função"));
        Funcao f = crudFuncao.pesquisarFuncao(id);
        if(f == null){
            JOptionPane.showMessageDialog(null, "Função não encontrada!");
        }else{
            IFrmAlterarFuncao ifrmAlterarFuncao = new IFrmAlterarFuncao(f);
            dpMenuPrincipal.add(ifrmAlterarFuncao);
            ifrmAlterarFuncao.setVisible(true);
        }
    }//GEN-LAST:event_jAlterarFuncaoActionPerformed

    private void jVisualizarFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisualizarFuncaoActionPerformed
        CrudFuncao crudFuncao = new CrudFuncao();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Função"));
        Funcao f = crudFuncao.pesquisarFuncao(id);
        if(f == null){
            JOptionPane.showMessageDialog(null, "Função não encontrada!");
        }else{
            IFrmVisualizarFuncao ifrmVisualizarFuncao = new IFrmVisualizarFuncao(f);
            dpMenuPrincipal.add(ifrmVisualizarFuncao);
            ifrmVisualizarFuncao.setVisible(true);
        }
    }//GEN-LAST:event_jVisualizarFuncaoActionPerformed

    private void jExcluirFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirFuncaoActionPerformed
        CrudFuncao crudFuncao = new CrudFuncao();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Função"));
        Funcao f = crudFuncao.pesquisarFuncao(id);
        if(f == null){
            JOptionPane.showMessageDialog(null, "Função não encontrada!");
        }else{
            IFrmExcluirFuncao ifrmExcluirFuncao = new IFrmExcluirFuncao(f);
            dpMenuPrincipal.add(ifrmExcluirFuncao);
            ifrmExcluirFuncao.setVisible(true);
        }
    }//GEN-LAST:event_jExcluirFuncaoActionPerformed

    private void jNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoFuncionarioActionPerformed
        IFrmNovoFuncionario ifrmNovoFuncionario = new IFrmNovoFuncionario();
        dpMenuPrincipal.add(ifrmNovoFuncionario);
        ifrmNovoFuncionario.setVisible(true);
    }//GEN-LAST:event_jNovoFuncionarioActionPerformed

    private void jAlterarFuncionaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarFuncionaroActionPerformed
        CrudFuncionario crudFuncionario = new CrudFuncionario();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Funcionário"));
        Funcionario f = crudFuncionario.pesquisarFuncionario(id);
        if(f == null){
            JOptionPane.showMessageDialog(null, "Funcionário não encontrado!");
        }else{
            IFrmAlterarFuncionario ifrmAlterarFuncionario = new IFrmAlterarFuncionario(f);
            dpMenuPrincipal.add(ifrmAlterarFuncionario);
            ifrmAlterarFuncionario.setVisible(true);
        }
    }//GEN-LAST:event_jAlterarFuncionaroActionPerformed

    private void jVisualizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisualizarFuncionarioActionPerformed
        CrudFuncionario crudFuncionario = new CrudFuncionario();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Funcionário"));
        Funcionario f = crudFuncionario.pesquisarFuncionario(id);
        if(f == null){
            JOptionPane.showMessageDialog(null, "Funcionário não encontrado!");
        }else{
            IFrmVisualizarFuncionario ifrmVisualizarFuncionario = new IFrmVisualizarFuncionario(f);
            dpMenuPrincipal.add(ifrmVisualizarFuncionario);
            ifrmVisualizarFuncionario.setVisible(true);
        }
    }//GEN-LAST:event_jVisualizarFuncionarioActionPerformed

    private void jExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirFuncionarioActionPerformed
        CrudFuncionario crudFuncionario = new CrudFuncionario();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Funcionário"));
        Funcionario f = crudFuncionario.pesquisarFuncionario(id);
        if(f == null){
            JOptionPane.showMessageDialog(null, "Funcionário não encontrado!");
        }else{
            IFrmExcluirFuncionario ifrmExcluirFuncionario = new IFrmExcluirFuncionario(f);
            dpMenuPrincipal.add(ifrmExcluirFuncionario);
            ifrmExcluirFuncionario.setVisible(true);
        }
    }//GEN-LAST:event_jExcluirFuncionarioActionPerformed

    private void jNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoProdutoActionPerformed
        IFrmNovoProduto ifrmNovoProduto = new IFrmNovoProduto();
        dpMenuPrincipal.add(ifrmNovoProduto);
        ifrmNovoProduto.setVisible(true);
    }//GEN-LAST:event_jNovoProdutoActionPerformed

    private void jAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarProdutoActionPerformed
        CrudProduto crudProduto = new CrudProduto();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do Produto"));
        Produto p = crudProduto.pesquisarProduto(id);
        if(p == null){
            JOptionPane.showMessageDialog(null, "Produto não encontrado!");
        }else{
            IFrmAlterarProduto ifrmAlterarProduto = new IFrmAlterarProduto(p);
            dpMenuPrincipal.add(ifrmAlterarProduto);
            ifrmAlterarProduto.setVisible(true);
        }
    }//GEN-LAST:event_jAlterarProdutoActionPerformed

    private void jVisualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisualizarProdutoActionPerformed
        CrudProduto crudProduto = new CrudProduto();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do Produto"));
        Produto p = crudProduto.pesquisarProduto(id);
        if(p == null){
            JOptionPane.showMessageDialog(null, "Produto não encontrado!");
        }else{
            IFrmVisualizarProduto ifrmVisualizarProduto = new IFrmVisualizarProduto(p);
            dpMenuPrincipal.add(ifrmVisualizarProduto);
            ifrmVisualizarProduto.setVisible(true);
        }
    }//GEN-LAST:event_jVisualizarProdutoActionPerformed

    private void jExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirProdutoActionPerformed
        CrudProduto crudProduto = new CrudProduto();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do Produto"));
        Produto p = crudProduto.pesquisarProduto(id);
        if(p == null){
            JOptionPane.showMessageDialog(null, "Produto não encontrado!");
        }else{
            IFrmExcluirProduto ifrmExcluirProduto = new IFrmExcluirProduto(p);
            dpMenuPrincipal.add(ifrmExcluirProduto);
            ifrmExcluirProduto.setVisible(true);
        }
    }//GEN-LAST:event_jExcluirProdutoActionPerformed

    private void listFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFuncaoActionPerformed
        IFrmListarFuncao ifrmListarFuncao = new IFrmListarFuncao();
        dpMenuPrincipal.add(ifrmListarFuncao);
        ifrmListarFuncao.setVisible(true);
    }//GEN-LAST:event_listFuncaoActionPerformed

    private void listClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClienteActionPerformed
        IFrmListarCliente ifrmListarCliente = new IFrmListarCliente();
        dpMenuPrincipal.add(ifrmListarCliente);
        ifrmListarCliente.setVisible(true);
    }//GEN-LAST:event_listClienteActionPerformed

    private void listEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEntregaActionPerformed
        IFrmListarEntrega ifrmListarEnterga = new IFrmListarEntrega();
        dpMenuPrincipal.add(ifrmListarEnterga);
        ifrmListarEnterga.setVisible(true);
    }//GEN-LAST:event_listEntregaActionPerformed

    private void listFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFuncionarioActionPerformed
        IFrmListarFuncionario ifrmListarFuncionario = new IFrmListarFuncionario();
        dpMenuPrincipal.add(ifrmListarFuncionario);
        ifrmListarFuncionario.setVisible(true);
    }//GEN-LAST:event_listFuncionarioActionPerformed

    private void listProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listProdutoActionPerformed
        IFrmListarProduto ifrmListarProduto = new IFrmListarProduto();
        dpMenuPrincipal.add(ifrmListarProduto);
        ifrmListarProduto.setVisible(true);
    }//GEN-LAST:event_listProdutoActionPerformed

    private void listUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUsuarioActionPerformed
        IFrmListarUsuario ifrmListarUsuario = new IFrmListarUsuario();
        dpMenuPrincipal.add(ifrmListarUsuario);
        ifrmListarUsuario.setVisible(true);
    }//GEN-LAST:event_listUsuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IFrmListarVenda ifrmListarVenda = new IFrmListarVenda();
        dpMenuPrincipal.add(ifrmListarVenda);
        ifrmListarVenda.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpMenuPrincipal;
    private javax.swing.JMenuItem jAlterarCliente;
    private javax.swing.JMenuItem jAlterarEnrtega;
    private javax.swing.JMenuItem jAlterarFuncao;
    private javax.swing.JMenuItem jAlterarFuncionaro;
    private javax.swing.JMenuItem jAlterarProduto;
    private javax.swing.JMenuItem jAlterarUsuario;
    private javax.swing.JMenuItem jAlterarVenda;
    private javax.swing.JMenu jCadastro;
    private javax.swing.JMenu jCliente;
    private javax.swing.JMenu jEntrega;
    private javax.swing.JMenuItem jExcluirCliente;
    private javax.swing.JMenuItem jExcluirEntrega;
    private javax.swing.JMenuItem jExcluirFuncao;
    private javax.swing.JMenuItem jExcluirFuncionario;
    private javax.swing.JMenuItem jExcluirProduto;
    private javax.swing.JMenuItem jExcluirUsuario;
    private javax.swing.JMenuItem jExcluirVenda;
    private javax.swing.JMenu jFuncao;
    private javax.swing.JMenu jFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jListagem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jNovaEntrega;
    private javax.swing.JMenuItem jNovaFuncao;
    private javax.swing.JMenuItem jNovaVenda;
    private javax.swing.JMenuItem jNovoCliente;
    private javax.swing.JMenuItem jNovoFuncionario;
    private javax.swing.JMenuItem jNovoProduto;
    private javax.swing.JMenuItem jNovoUsuario;
    private javax.swing.JMenu jProduto;
    private javax.swing.JMenu jUsuario;
    private javax.swing.JMenu jVenda;
    private javax.swing.JMenuItem jVisualizarCliente;
    private javax.swing.JMenuItem jVisualizarEntrega;
    private javax.swing.JMenuItem jVisualizarFuncao;
    private javax.swing.JMenuItem jVisualizarFuncionario;
    private javax.swing.JMenuItem jVisualizarProduto;
    private javax.swing.JMenuItem jVisualizarUsuario;
    private javax.swing.JMenuItem jVisualizarVenda;
    private javax.swing.JMenuItem listCliente;
    private javax.swing.JMenuItem listEntrega;
    private javax.swing.JMenuItem listFuncao;
    private javax.swing.JMenuItem listFuncionario;
    private javax.swing.JMenuItem listProduto;
    private javax.swing.JMenuItem listUsuario;
    private javax.swing.JMenuBar mbMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
