/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import static bancoDados.dataBase.lstAluno;
import CRUD.listAluno;
import javax.swing.JOptionPane;
import trabalhojava.Aluno;
/**
 *
 * @author Alexandre
 */
public class ifrmRemoveAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmRemoveAluno
     */
    private listAluno aluno = new listAluno();
    public ifrmRemoveAluno() {
        initComponents();
        
        rmAlunoBox.removeAllItems();
        for(Aluno opc: lstAluno){
            rmAlunoBox.addItem(opc.getNome());
        }
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        rmAluno = new javax.swing.JButton();
        cancAluno = new javax.swing.JButton();
        rmAlunoBox = new javax.swing.JComboBox<>();

        jToggleButton1.setText("jToggleButton1");

        setTitle("Remover Aluno");

        jLabel2.setText("Selecione o Aluno:");
        jLabel2.setToolTipText("");

        rmAluno.setText("Remover");
        rmAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmAlunoActionPerformed(evt);
            }
        });

        cancAluno.setText("Cancela");
        cancAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancAlunoActionPerformed(evt);
            }
        });

        rmAlunoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(rmAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancAluno)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rmAlunoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmAlunoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rmAluno)
                    .addComponent(cancAluno))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancAlunoActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancAlunoActionPerformed

    private void rmAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmAlunoActionPerformed
        String op1=(String) rmAlunoBox.getSelectedItem(); 
        for(Aluno op2 : lstAluno){          
            if(op2.getNome().equals(op1)){
                rmAlunoBox.removeItem(op2.getNome());
                aluno.remover(op2);
                
    }                                               

    }
    }//GEN-LAST:event_rmAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancAluno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton rmAluno;
    private javax.swing.JComboBox<String> rmAlunoBox;
    // End of variables declaration//GEN-END:variables
}
