/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import static bancoDados.dataBase.lstProfessor;
import javax.swing.JOptionPane;
import trabalhojava.Professor;
/**
 *
 * @author Alexandre
 */
public class ifrmConsultaProfessor extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmConsultaProfessor
     */
    public ifrmConsultaProfessor() {
        initComponents();
        
        professorBox.removeAllItems();
        for(Professor ops: lstProfessor){
            professorBox.addItem(ops.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        professorBox = new javax.swing.JComboBox<>();
        consProfessor = new javax.swing.JButton();
        cancProfessor = new javax.swing.JButton();

        setTitle("Consultar Professor");

        jLabel1.setText("Selecione o Professor:");

        professorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        consProfessor.setText("Consultar");
        consProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consProfessorActionPerformed(evt);
            }
        });

        cancProfessor.setText("Cancelar");
        cancProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(professorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(consProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancProfessor)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consProfessor)
                    .addComponent(cancProfessor))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancProfessorActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancProfessorActionPerformed

    private void consProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consProfessorActionPerformed
        String op1 = (String) professorBox.getSelectedItem();
        for(Professor op2 : lstProfessor){
            if(op2.getNome().equals(op1)){
                JOptionPane.showMessageDialog(
                null,
                "Nome Professor: "+op2.getNome()+"\n"+
                "Matrícula Professor: "+op2.getMatricula()+"\n"
                );
                break;
            }
        }
    }//GEN-LAST:event_consProfessorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancProfessor;
    private javax.swing.JButton consProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> professorBox;
    // End of variables declaration//GEN-END:variables
}
