/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import CRUD.listAula;
import javax.swing.JOptionPane;


import static bancoDados.dataBase.lstMateria;
import static bancoDados.dataBase.lstProfessor;

import javax.swing.JDesktopPane;
import trabalhojava.Aula;

import trabalhojava.Materia;
import trabalhojava.Professor;
/**
 *
 * @author Alexandre
 */
public class ifrmAdicionaAula extends javax.swing.JInternalFrame {
//public ArrayList<Materia>lst = new ArrayList<>();
         //String op5;
    /**
     * Creates new form ifrmAdicionaAula
     */
    private JDesktopPane cadAluno;
    public ifrmAdicionaAula(JDesktopPane cadAluno) {
        initComponents();
        this.cadAluno = cadAluno;
        
        this.txtCodAula.setText(Integer.toString(trabalhojava.Aula.nextID));
        
        //System.out.println(trabalhojava.Aula.nextID);
        
        this.txtCodAula.setEnabled(false);
        
        
        
        materiaBox.removeAllItems();
        for (Materia opc: lstMateria){
            materiaBox.addItem(opc.getNome());
        }
        
        professorBox.removeAllItems();
        for (Professor p: lstProfessor){
            professorBox.addItem(p.getNome());
        }
        
        qtdeAulaBox.removeAllItems();
        for(int i = 1; i<=4; i++){
            qtdeAulaBox.addItem(Integer.toString(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDataAula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        professorBox = new javax.swing.JComboBox<>();
        qtdeAulaBox = new javax.swing.JComboBox<>();
        cadAddAula = new javax.swing.JButton();
        cancAddAula = new javax.swing.JButton();
        txtCodAula = new javax.swing.JTextField();
        materiaBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();

        setTitle("Adicionar Aula");

        jLabel1.setText("Codigo da Aula:");

        jLabel2.setText("Data da Aula:");

        jLabel3.setText("Quantidade de Aula:");

        jLabel4.setText("Matéria:");

        jLabel5.setText("Professor:");

        professorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        qtdeAulaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdeAulaBoxActionPerformed(evt);
            }
        });

        cadAddAula.setText("Cadastrar");
        cadAddAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAddAulaActionPerformed(evt);
            }
        });

        cancAddAula.setText("Cancelar");
        cancAddAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancAddAulaActionPerformed(evt);
            }
        });

        materiaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("sala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadAddAula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancAddAula)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(120, 120, 120))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodAula)
                                .addGap(97, 97, 97))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDataAula)
                                .addGap(97, 97, 97)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(professorBox, 0, 173, Short.MAX_VALUE)
                            .addComponent(materiaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(qtdeAulaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(materiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(professorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdeAulaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadAddAula)
                    .addComponent(cancAddAula))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancAddAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancAddAulaActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancAddAulaActionPerformed

    private void qtdeAulaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdeAulaBoxActionPerformed
       int op = qtdeAulaBox.getSelectedIndex();
       
       System.out.println(op+1);
       
       
       
        
            
       // } else {
        //}
    }//GEN-LAST:event_qtdeAulaBoxActionPerformed

    private void cadAddAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAddAulaActionPerformed
        Aula auxAula = new Aula();
        int op1 = this.qtdeAulaBox.getSelectedIndex();
        String op2 = (String) materiaBox.getSelectedItem();
        String op3 = (String) professorBox.getSelectedItem();
        listAula a = new listAula();
        String op4 = (String) this.txtDataAula.getText();
        int op5 = trabalhojava.Aula.nextID;
        auxAula.setData(op4);
        auxAula.setId(op5 -1);
        auxAula.setQtde(op1);
        a.inserir(auxAula);
        
        
        
        
        
        JOptionPane.showMessageDialog(
                this,            
                "Codigo da Aula: "+this.txtCodAula.getText()+"\n"+
                "Data da Aula: "+this.txtDataAula.getText()+"\n"+
                "Quantidade de Aula: "+(op1+1)+"\n"+
                "Matéria: "+op2+"\n"+
                "Professor: "+op3+"\n"        
        );
        presencaAluno telaPresenca = new presencaAluno(txtSala.getText(),txtCodAula.getText());
        cadAluno.add(telaPresenca);
        telaPresenca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadAddAulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadAddAula;
    private javax.swing.JButton cancAddAula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> materiaBox;
    private javax.swing.JComboBox<String> professorBox;
    private javax.swing.JComboBox<String> qtdeAulaBox;
    private javax.swing.JTextField txtCodAula;
    private javax.swing.JTextField txtDataAula;
    private javax.swing.JTextField txtSala;
    // End of variables declaration//GEN-END:variables

    private String getSelectedIndex() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String toString(int selectedIndex) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  
}
