/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import static bancoDados.dataBase.lstAluno;
import javax.swing.JOptionPane;
import trabalhojava.Aluno;

/**
 *
 * @author Alexandre
 */
public class ifrmConsultaAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form conAluno
     */
    public ifrmConsultaAluno() {
        initComponents();
        
        alunoBox1.removeAllItems();
        for(Aluno opc: lstAluno){
            alunoBox1.addItem(opc.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        consAluno = new javax.swing.JButton();
        cancConsultaAluno = new javax.swing.JButton();
        alunoBox1 = new javax.swing.JComboBox<>();

        jLabel3.setText("jLabel3");

        setTitle("Consultar Aluno");

        jLabel2.setText("Selecione o Aluno:");

        consAluno.setText("OK");
        consAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consAlunoActionPerformed(evt);
            }
        });

        cancConsultaAluno.setText("Cancela");
        cancConsultaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancConsultaAlunoActionPerformed(evt);
            }
        });

        alunoBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(consAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancConsultaAluno)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(alunoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alunoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consAluno)
                    .addComponent(cancConsultaAluno))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancConsultaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancConsultaAlunoActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancConsultaAlunoActionPerformed

    private void consAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consAlunoActionPerformed
        String op1=(String) alunoBox1.getSelectedItem(); 
        for(Aluno op2 : lstAluno){          
            if(op2.getNome().equals(op1)){
                System.out.println(op2.getNome());
                JOptionPane.showMessageDialog(
                null,
                "Nome Aluno: "+op2.getNome()+"\n"+
                "Matrícula Aluno: "+op2.getMatricula()+"\n"+
                "Sala: "+op2.getSala()+"\n"
                        
         );      
       
                break;
        }
    
         
    }//GEN-LAST:event_consAlunoActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alunoBox1;
    private javax.swing.JButton cancConsultaAluno;
    private javax.swing.JButton consAluno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
