/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import static bancoDados.dataBase.lstMateria;
import javax.swing.JOptionPane;
import trabalhojava.Materia;
/**
 *
 * @author Alexandre
 */
public class ifrmConsultaMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmConsultarMatéria
     */
    public ifrmConsultaMateria() {
        initComponents();
        
        materiaBox.removeAllItems();
        for(Materia opc: lstMateria){
            materiaBox.addItem(opc.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        materiaBox = new javax.swing.JComboBox<>();
        consMateria = new javax.swing.JButton();
        cancMateria = new javax.swing.JButton();

        setTitle("Consultar Matéria");

        jLabel1.setText("Selecione a Matéria:");

        materiaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        consMateria.setText("Consultar");
        consMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consMateriaActionPerformed(evt);
            }
        });

        cancMateria.setText("Cancelar");
        cancMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(consMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancMateria)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consMateria)
                    .addComponent(cancMateria))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consMateriaActionPerformed
        String op1=(String) materiaBox.getSelectedItem(); 
        for(Materia op2 : lstMateria){          
            if(op2.getNome().equals(op1)){
                System.out.println(op2.getNome());
                JOptionPane.showMessageDialog(
                null,
                "Nome Matéria: "+op2.getNome()+"\n"+
                "Código Matéria: "+op2.getId()+"\n"+
                "Quantidade de Aulas no Período: "+op2.getQtdAula()+"\n"
                        
         );      
       
                break;
        }
    }//GEN-LAST:event_consMateriaActionPerformed
 }
    private void cancMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancMateriaActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancMateria;
    private javax.swing.JButton consMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> materiaBox;
    // End of variables declaration//GEN-END:variables
}
