/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import static bancoDados.dataBase.lstAluno;
import javax.swing.JOptionPane;
import trabalhojava.Aluno;

/**
 *
 * @author Alexandre
 */
public class ifrmAtualizaAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmAtualizaAluno
     */
    public ifrmAtualizaAluno() {
        initComponents();
        
        atAlunoBox.removeAllItems();
        for(Aluno opc: lstAluno){
            atAlunoBox.addItem(opc.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        atualizaAtAluno = new javax.swing.JButton();
        cancAtAluno = new javax.swing.JButton();
        atAlunoBox = new javax.swing.JComboBox<>();

        setTitle("Atualizar Aluno");

        jLabel2.setText("Selecione o Aluno");

        atualizaAtAluno.setText("Atualizar");
        atualizaAtAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaAtAlunoActionPerformed(evt);
            }
        });

        cancAtAluno.setText("Cancela");
        cancAtAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancAtAlunoActionPerformed(evt);
            }
        });

        atAlunoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atualizaAtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancAtAluno)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(atAlunoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atAlunoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizaAtAluno)
                    .addComponent(cancAtAluno))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancAtAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancAtAlunoActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancAtAlunoActionPerformed

    private void atualizaAtAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaAtAlunoActionPerformed
        String op1=(String) atAlunoBox.getSelectedItem(); 
        String aux;
        for(Aluno op2 : lstAluno){          
            if(op2.getNome().equals(op1)){
                aux = JOptionPane.showInputDialog(
                null,
                "Nome Aluno: "+op2.getNome()+"\n"+
                "Digite o Novo Nome: \n"   
                        
                );
                if(!aux.isEmpty()){
                    op2.setNome(aux);
                }
                
                
                aux = JOptionPane.showInputDialog(
                null,
                "Sala: "+op2.getSala()+"\n"+
                "Digite a Nova Sala: \n"       
                );
               
               if(!aux.isEmpty()){
                        op2.setSala(aux);
                }
    }//GEN-LAST:event_atualizaAtAlunoActionPerformed

    }
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> atAlunoBox;
    private javax.swing.JButton atualizaAtAluno;
    private javax.swing.JButton cancAtAluno;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
