/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import CRUD.listAluno;
import CRUD.listAula;
import CRUD.listPresenca;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import bancoDados.dataBase;
import javax.swing.JOptionPane;
import trabalhojava.Aluno;
import trabalhojava.Aula;
import trabalhojava.Presenca;

/**
 *
 * @author Alexandre
 */
public class presencaAluno extends javax.swing.JInternalFrame {
            listPresenca crudp = new listPresenca();
            listAluno cruda = new listAluno();
            String aula;
            String sala;
            //listAula crudal = new listAula();
            Presenca pr = new Presenca();
            
    /**
     * Creates new form presencaAluno
     */
    private ArrayList<JCheckBox> cbPresencas = new ArrayList<>();
    public presencaAluno(String sala,String Aula) {
        initComponents();
        this.sala = sala;
        this.aula = aula;
        for(Aluno a: cruda.ler()){
            if(a.getSala().equals(sala))
            cbPresencas.add(new JCheckBox(a.getNome()));
        }
        /*
        cbPresencas.add(new JCheckBox("teste1"));
        cbPresencas.add(new JCheckBox("teste2"));
        cbPresencas.add(new JCheckBox("teste3"));
        cbPresencas.add(new JCheckBox("teste4"));
        cbPresencas.add(new JCheckBox("teste5"));
        */
        panelPresenca.setLayout(new GridLayout(cbPresencas.size(),1));
        for(JCheckBox box: cbPresencas){
            panelPresenca.add(box);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPresenca = new javax.swing.JPanel();
        btCadPresenca = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Presença");

        javax.swing.GroupLayout panelPresencaLayout = new javax.swing.GroupLayout(panelPresenca);
        panelPresenca.setLayout(panelPresencaLayout);
        panelPresencaLayout.setHorizontalGroup(
            panelPresencaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );
        panelPresencaLayout.setVerticalGroup(
            panelPresencaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        btCadPresenca.setText("Cadastrar");
        btCadPresenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadPresencaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelPresenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btCadPresenca)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPresenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btCadPresenca)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadPresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadPresencaActionPerformed
        // TODO add your handling code here:
        String r = "";
        for(JCheckBox p: cbPresencas){
           pr.setAluno(p.getText());
           pr.setAula(aula);
                    if(p.isSelected()){                   
                    pr.setPresenca(true);
                    r+=p.getText()+"\n";
                    }else
                    pr.setPresenca(false);
 
        }
            crudp.inserir(pr);
            JOptionPane.showMessageDialog(null,"Alunos Presentes: \n"+r+"\n");
            //JOptionPane.showMessageDialog(null, p.isSelected());
            //System.out.println(p.isSelected());
        
    }//GEN-LAST:event_btCadPresencaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadPresenca;
    private javax.swing.JPanel panelPresenca;
    // End of variables declaration//GEN-END:variables
}
