/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import crud.VeiculoCRUD;
import crud.CategoriaCRUD;
import domain.Veiculo;
import domain.Cliente;
import domain.Categoria;
import crud.ClienteCRUD;
import database.DataBase;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class IFrmCadastrarVeiculo extends javax.swing.JInternalFrame {
    
    VeiculoCRUD CRUD;
    Veiculo vei;
    ClienteCRUD CRUDclie;
    CategoriaCRUD CRUDcat;
    Cliente cliaux;
    Categoria cataux;
    int aux;
    ArrayList<Cliente> lstCliente = new ArrayList();
    ArrayList<Categoria> lstCategoria = new ArrayList();
    
    /**
     * Creates new form IFrmCadastrarVeiculo
     */
    public IFrmCadastrarVeiculo(int tipo, String nomeBt, String titulo) {
        aux = tipo;
        CRUD = new VeiculoCRUD();
        CRUDclie = new ClienteCRUD();
        CRUDcat = new CategoriaCRUD();
        //Cliente cliaux;
        //Categoria cataux;
        initComponents();
        // Altera o titulo da janela
        this.setTitle(titulo);
        // Altera o lbTitulo da janela
        this.setTitulo(titulo);
        // Muda o texto do botão conforme a ação(Alterar, Visualizar e Remover)
        btCadastrar.setText(nomeBt);
        // Limpa e preenche o combo box cbUf com os estados brasileiros
        cbCliente.removeAllItems();
        lstCliente = database.DataBase.lstCliente;
        cbCategoria.removeAllItems();
        lstCategoria = database.DataBase.lstCategoria;
        if(!lstCliente.isEmpty() && !lstCategoria.isEmpty()){
            for (Cliente i : lstCliente) {
                cbCliente.addItem(i.getCpf());
            }
            for (Categoria i : lstCategoria) {
                cbCategoria.addItem(i.getId()+i.getCategoria());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCor = new javax.swing.JTextField();
        lbCategoria = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        lbPlaca = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        tfPlaca = new javax.swing.JTextField();
        lbCor = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        cbCategoria = new javax.swing.JComboBox<>();

        lbCategoria.setText("Categoria:");

        lbCliente.setText("Cliente:");

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitulo.setText("Cadastro de Veículos");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        lbPlaca.setText("Placa:");

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        lbCor.setText("Cor:");

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbCor)
                                .addComponent(lbCategoria)
                                .addComponent(lbCliente))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(btCadastrar)
                            .addGap(18, 18, 18)
                            .addComponent(btCancelar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(lbTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(lbPlaca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPlaca)
                    .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCor)
                    .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategoria)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCliente)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btCancelar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        String placa        = tfPlaca.getText();
        String cor          = tfCor.getText();
        String categoria    = String.valueOf(cbCategoria.getSelectedItem());
        String cliente      = String.valueOf(cbCliente.getSelectedItem());
        
        cliaux = CRUDclie.ler(cliente);
        
        String categoria2 = categoria.replaceAll("[^0-9]", "");
        int cat = Integer.parseInt(categoria2);
        cataux = CRUDcat.ler(cat); //cat
        vei = new Veiculo(placa, cor, cataux, cliaux); // placa, cor
        
        // Switch case para mudar a ação do botão conforme a ação(Alterar, Visualizar e Remover)
        switch(aux){
            case 0:
                CRUD.inserir(vei);
                limparTela();
            break;
            case 1:
                CRUD.alterar(placa, vei);
                limparTela();
            break;
            case 2:
                this.dispose();
            break;
            case 3:
                vei = CRUD.ler(placa);
                CRUD.remove(vei);
                limparTela();
            break;
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbCor;
    private javax.swing.JLabel lbPlaca;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField tfCor;
    private javax.swing.JTextField tfPlaca;
    // End of variables declaration//GEN-END:variables

public void limparTela(){
    tfPlaca.setText("");
    tfCor.setText("");
}

public void setTitulo(String titulo){
    lbTitulo.setText(titulo);
}

public void setVeiculo(Veiculo veiculo){
    tfPlaca.setText(veiculo.getPlaca());
    tfCor.setText(veiculo.getCor());
    cbCategoria.setSelectedItem(veiculo.getCategoria());
    cbCliente.setSelectedItem(veiculo.getCliente());
}

public void setDesabilitarInputs(int opc){
    if(opc == 0){
        tfPlaca.setEditable(false);
        tfCor.setEditable(false);
    } else {
        tfPlaca.setEditable(false);
    }
}

public int verificaExistClient(){
    if(lstCliente.isEmpty()){
        JOptionPane.showMessageDialog(null, "Antes de cadastrar um veiculo, cadastre um Cliente");
        return 0;
    } else {
        return 1;
    }
}

public int verificaExistCatg(){
    if(lstCategoria.isEmpty()){
        JOptionPane.showMessageDialog(null, "Antes de cadastrar um veiculo, cadastre uma Categoria");
        return 0;
    } else {
        return 1;
    }
}

public void fecha(){
    this.dispose();
}
}
