/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import crud.FuncionarioCRUD;
import domain.Funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class IFrmPesquisarFuncionario extends javax.swing.JInternalFrame {
    FuncionarioCRUD CRUD;
    Funcionario func;
    int aux;
    /**
     * Creates new form IFrmPesquisarFuncionario
     */
    public IFrmPesquisarFuncionario(int tipo) {
        CRUD = new FuncionarioCRUD();
        initComponents();
        aux = tipo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        tfCpf = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitulo.setText("Pesquisar Cliente");

        lbCpf.setText("CPF:");

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbTitulo)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpf)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar)
                    .addComponent(btCancelar))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        String cpf = tfCpf.getText();
        func = CRUD.ler(cpf);
        
        if(func == null){
            JOptionPane.showMessageDialog(null, "Não encontrado");
        } else {
            // Constroi a janela conforme a ação(Alterar, visualizar e remover)
            switch(aux){
                case 1:
                    IFrmCadastrarFuncionario editFornFrm = new IFrmCadastrarFuncionario(
                        1, "Salvar", "Alteração de Funcionário");
                    FrmMenuPrincipal.dpPrincipal.add(editFornFrm);
                    editFornFrm.setFuncionario(func);
                    editFornFrm.setDesabilitarInputs(1);
                    editFornFrm.setVisible(true);
                break;
                case 2:
                    IFrmCadastrarFuncionario visuaFornFrm = new IFrmCadastrarFuncionario(
                        2, "Fechar", "Visualizar Funcionário");
                    FrmMenuPrincipal.dpPrincipal.add(visuaFornFrm);
                    visuaFornFrm.setFuncionario(func);
                    visuaFornFrm.setDesabilitarInputs(0);
                    visuaFornFrm.setVisible(true);
                break;
                case 3:
                    IFrmCadastrarFuncionario removeFornFrm = new IFrmCadastrarFuncionario(
                        3, "Remover", "Remover Funcionário");
                    FrmMenuPrincipal.dpPrincipal.add(removeFornFrm);
                    removeFornFrm.setFuncionario(func);
                    removeFornFrm.setDesabilitarInputs(0);
                    removeFornFrm.setVisible(true);
                break;
                default:
                    System.out.println("Fazer nada");
                break;
            }

        }
        tfCpf.setText("");

    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        //tfCpf.setText("");
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField tfCpf;
    // End of variables declaration//GEN-END:variables
}
