/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import crud.*;
import domain.*;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author Jovane
 */
public class IFrmEstacionar extends javax.swing.JInternalFrame {
    VagaCRUD vagacrud = new VagaCRUD();
    VeiculoCRUD veicrud = new VeiculoCRUD();
    FuncionarioCRUD funcrud = new FuncionarioCRUD();
    public EstacionadoCRUD estacionado = new EstacionadoCRUD();
    Estacionado estac = new Estacionado();
    Vaga vag = new Vaga();
    
    public IFrmEstacionar(Vaga vaga) {
        initComponents();
        if(!veicrud.listar().isEmpty())
            for(Veiculo veic : veicrud.listar()){
                cbVeiculo.addItem(veic.getPlaca());
        if(!funcrud.listar().isEmpty()){
            for(Funcionario func : funcrud.listar()){
                cbFuncionario.addItem(func.getNome());
            }
        this.vag = vaga;
        }else{
        JOptionPane.showMessageDialog(null,"Nenhum funcionario a ser listado \nPor favor cadestre alguma veiculo");
        
        }
        
        }else{
            JOptionPane.showMessageDialog(null,"Nenhum veiculo a ser listado \nPor favor cadestre alguma veiculo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbVeiculo = new javax.swing.JLabel();
        cbVeiculo = new javax.swing.JComboBox<>();
        lbHoraInicial = new javax.swing.JLabel();
        txHoraI = new javax.swing.JFormattedTextField();
        txtHoraF = new javax.swing.JFormattedTextField();
        lbHoraF = new javax.swing.JLabel();
        lbValorTotal = new javax.swing.JLabel();
        lbFuncionario = new javax.swing.JLabel();
        cbFuncionario = new javax.swing.JComboBox<>();
        btOk = new javax.swing.JButton();
        btFinalizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lbVeiculo.setText("VEICULO");

        cbVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbHoraInicial.setText("HORA INICAL");

        lbHoraF.setText("HORA FINAL");

        lbValorTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbValorTotal.setText("VALOR");

        lbFuncionario.setText("FUNCIONARIO");

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btFinalizar.setText("FINALIZAR");
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });

        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbHoraInicial)
                                .addComponent(lbVeiculo)
                                .addComponent(lbHoraF)
                                .addComponent(lbFuncionario))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHoraF)
                                .addComponent(cbVeiculo, 0, 173, Short.MAX_VALUE)
                                .addComponent(txHoraI)
                                .addComponent(cbFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lbValorTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVeiculo)
                    .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHoraInicial)
                    .addComponent(txHoraI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoraF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFuncionario)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbValorTotal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk)
                    .addComponent(btFinalizar)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
       estac.setTempoInical(Calendar.getInstance().getTime());
       vag.setVeiculo(veicrud.listar().get(cbVeiculo.getSelectedIndex()));
       estac.setVaga(vag);
       estac.setFuncionario(funcrud.listar().get(cbFuncionario.getSelectedIndex()));
    }//GEN-LAST:event_btOkActionPerformed

    private void btFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarActionPerformed
        long totalM;
        totalM = (Calendar.getInstance().getTime().getTime() - estac.getTempoInical().getTime())/1000*60*60;
        estac.setValorTotal(totalM*estac.getVaga().getVeiculo().getCategoria().getValorHora()/60);
    }//GEN-LAST:event_btFinalizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizar;
    private javax.swing.JButton btOk;
    private javax.swing.JComboBox<String> cbFuncionario;
    private javax.swing.JComboBox<String> cbVeiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbFuncionario;
    private javax.swing.JLabel lbHoraF;
    private javax.swing.JLabel lbHoraInicial;
    private javax.swing.JLabel lbValorTotal;
    private javax.swing.JLabel lbVeiculo;
    private javax.swing.JFormattedTextField txHoraI;
    private javax.swing.JFormattedTextField txtHoraF;
    // End of variables declaration//GEN-END:variables
}
