/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import crud.EstacionadoCRUD;
import crud.VagaCRUD;
import domain.Estacionado;
import domain.Vaga;

/**
 *
 * @author Jovane
 */
public class PainelVaga extends javax.swing.JPanel {
    Vaga vag;
    SimpleDateFormat formato = new SimpleDateFormat("HH:mm:ss");
    EstacionadoCRUD estCrud = new EstacionadoCRUD();
    VagaCRUD vagaCrud = new VagaCRUD();
    Date agora = Calendar.getInstance().getTime();
    Estacionado estacionado;
    IFrmEstacionar estacionar;
    
    public PainelVaga(Vaga vaga) { 
       
        initComponents();
        
        this.vag = vaga;
        estacionar = new IFrmEstacionar(vag); 
        lbNumero.setText(String.valueOf(vaga.getNumero()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNumero = new javax.swing.JLabel();
        lbTmpInicial = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbNumero.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNumero.setText("0");

        lbTmpInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTmpInicial.setText("Temp Inical");

        btAdicionar.setText("ADICIONAR");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lbNumero))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbTmpInicial)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTmpInicial)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
       
        lbTmpInicial.setText("INICIO: "+formato.format(Calendar.getInstance().getTime()));        
        estacionar.setVisible(true);
        btAdicionar.setText(vag.getVeiculo().getPlaca());
       
    }//GEN-LAST:event_btAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbTmpInicial;
    // End of variables declaration//GEN-END:variables

}
